services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - microservices-network

  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "50001:50001"
    environment:
      - ASPNETCORE_URLS=http://+:50001
      - CONSUL_HOST=consul
    depends_on:
      - consul
    networks:
      - microservices-network

  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "50002:50002"
    environment:
      - ASPNETCORE_URLS=http://+:50002
      - CONSUL_HOST=consul
    depends_on:
      - consul
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "50000:50000"
      - "50005:50005"
    environment:
      - ASPNETCORE_URLS=http://+:50000
      - CONSUL_HOST=consul
    depends_on:
      - consul
      - product-service
      - order-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
