global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:50000']

  - job_name: 'product-services'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product-service-1:50001', 'product-service-2:50001', 'product-service-3:50001']

  - job_name: 'order-services'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service-1:50002', 'order-service-2:50002']